### ISSUE TITLE
Destructor of filters not called anymore

### ISSUE THREAD

**Issue by jpsdr** [pinterf/mvtools#10] opened 2017-08-23 09:46 UTC
Hello.
Try to find out a deadlock cause, i've noticed that for exemple, when i run this script :

AviSource("SP_IVTC.avi",False,"YV12")
nnedi3()
super     =    MSuper (hpad=16, vpad=16)
bvec2     =    MAnalyse (super, isb = true, delta = 2)
bvec1     =    MAnalyse (super, isb = true, delta = 1)
fvec1     =    MAnalyse (super, isb = false, delta = 1)
fvec2     =    MAnalyse (super, isb = false, delta = 2)
MDegrain2 (super, bvec1, fvec1, bvec2, fvec2)

the destructor of **nnedi3** is not called anymore when i close the script (in VDub).
If i remove **MDegrain2**, when i close the script, the destructor is called again.
It's not specific to nnedi3, it happens with all my filters. Didn't test on others third-party filters.
For now, i'm more thinking there an issue in **mvtools** than my filters.

**Comment by pinterf** [comment] 2017-08-28 08:53
Thanks, the problem is similar to https://github.com/pinterf/mvtools/issues/5 

2.7.0.22d is not affected, from 2.7.1.22 the problem exists, this latter was build with VS2015 again. But it had other big modifications.

It can also be reproduced also by opening a command prompt, and running a batch file that is feeding the script to x264.exe and break it with ctrl-c. The problematic version will never prompt for "Do you really want to interrupt batch... Y/N".

**Comment by pinterf** [comment] 2017-09-01 10:55
Fixed in 2.7.22

**Closed as completed by pinterf** 2017-09-01 10:55 UTC
